meta_title: "Roger Vilder - Artiste cinétique"
meta_description: "Le travail de Roger Vilder est centré autour des concepts de mouvement et de temporalité dans toute son œuvre.
Dès le début de sa carrière dans les années 60, il explore le cinétisme par le mouvement réel au travers de matériaux divers allant de la mécanique motorisée, des recherches numériques au néon.
Il exprime par le biais d'une géométrie simple, ses observations du monde des formes, à laquelle il donne un mouvement lent continu, de croissance et décroissance dans des cycles répétitifs ou aléatoires.
Se faisant, formes et couleurs sont mises en relation les unes avec les autres, privilégiant ainsi l'harmonie de la composition dans un continuum spatio-temporel d'une sensualité toute organique."
meta_image: "logo.png" # "logo_rv.png" should exist in `app/assets/images/`
#twitter_account: "@product_twitter_account"   # required for Twitter Cards
